apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: si9jvgmhg-python
  janus-idp.io/tekton: si9jvgmhg-python
  backstage.io/kubernetes-id: si9jvgmhg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: si9jvgmhg-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
