apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: si9jvgmhg-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: si9jvgmhg-python 
  name: si9jvgmhg-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: si9jvgmhg-python 
